- hosts: web
  roles:
    - role: xbuild
      become_user: isucon
  tasks:
    - lineinfile:
        path: /home/isucon/.profile
        regexp: 'GOPATH=.*'
        line: export GOPATH=/home/isucon/go
      become_user: isucon
    - lineinfile:
        path: /home/isucon/.profile
        line: export PATH=$GOPATH/bin
        state: absent
      become_user: isucon
    - lineinfile:
        path: /home/isucon/.profile
        line: export PATH=$GOPATH/bin:$PATH
      become_user: isucon
    - shell:
        cmd: bash -lc 'go get -u github.com/golang/dep/cmd/dep'
        creates: /home/isucon/go/bin/dep
      become_user: isucon
    - get_url:
        url: https://getcomposer.org/download/1.7.2/composer.phar
        checksum: "sha256:ec3428d049ae8877f7d102c2ee050dbd51a160fc2dde323f3e126a3b3846750e"
        dest: /home/isucon/local/php/bin/composer
        mode: 0755
      become_user: isucon
    - git:
        repo: https://github.com/isucon/isucon7-final 
        dest: /tmp/cco
    - stat:
        path: /home/isucon/webapp
      register: webapp
    - synchronize:
        src: /tmp/cco/webapp
        dest: /home/isucon
      become_user: isucon
      delegate_to: "{{ inventory_hostname }}"
      when: not webapp.stat.exists
    - copy:
        src: /tmp/cco/{{ item.src }}
        dest: /etc/nginx/sites-available/{{ item.dest }}
        remote_src: yes
      notify: Reload nginx
      loop:
        - src: files/cco.nginx.conf
          dest: cco.nginx.conf
        - src: files/cco.php.nginx.conf
          dest: cco.php.nginx.conf
    - file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Reload nginx
    - file:
        src: ../sites-available/cco.nginx.conf
        dest: /etc/nginx/sites-enabled/cco.nginx.conf
        state: link
      notify: Reload nginx
    - copy:
        src: /tmp/cco/{{ item.src }}
        dest: /etc/systemd/system/{{ item.dest }}
        remote_src: yes
      register: systemd_service
      loop:
        - src: files/cco.ruby.service
          dest: /cco.ruby.service
        - src: files/cco.perl.service
          dest: cco.perl.service
        - src: files/cco.nodejs.service
          dest: cco.nodejs.service
        - src: files/cco.golang.service
          dest: cco.golang.service
        - src: files/cco.python.service
          dest: cco.python.service
        - src: files/cco.php.service
          dest: cco.php.service
    - systemd:
        daemon_reload: yes
      when: systemd_service is changed
    - template:
        src: env.sh.j2
        dest: /home/isucon/env.sh
        owner: isucon
        group: isucon
    - shell:
        cmd: bash -lc '{{ item.cmd }}'
        chdir: "{{ item.chdir }}"
        creates: "{{ item.creates | default(omit) }}"
      become_user: isucon
      loop: "{{ webapp_init }}"
    - systemd:
        name: nginx
        state: started
        enabled: yes
    - systemd:
        name: cco.python
        state: started
        enabled: yes
      ignore_errors: yes
    - file:
        path: /tmp/cco
        state: absent

  handlers:
    - name: Reload nginx
      systemd:
        name: nginx
        state: reloaded

- hosts: db
  tasks:
    - git:
        repo: https://github.com/isucon/isucon7-final 
        dest: /tmp/cco
    - stat:
        path: /home/isucon/db
      register: db
    - synchronize:
        src: /tmp/cco/db
        dest: /home/isucon
      become_user: isucon
      delegate_to: "{{ inventory_hostname }}"
      when: not db.stat.exists
    - pip:
        name: MySQL-python
    - mysql_db:
        name: isudb
      register: isucon_db
    - command:
        cmd: /home/isucon/db/init.sh
      when: isucon_db is changed
    - mysql_user:
        name: "{{ isucon_db_user }}"
        password: "{{ isucon_db_pass }}"
        host: "{{ item }}"
        priv: 'isudb.*:ALL'
      loop:
        - "localhost"
        - "%"
    - ini_file:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        section: mysqld
        option: bind-address
        value: 0.0.0.0
      notify: Restart mysql
    - file:
        path: /tmp/cco
        state: absent

  handlers:
    - name: Restart mysqld
      systemd:
        name: mysql
        state: restarted
